// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm7Zj65lfPqFQ1pEScq773BBDS-2h1cmY',
    appId: '1:386190378061:web:8b9f26d91d0f6b061a8804',
    messagingSenderId: '386190378061',
    projectId: 'entertainment-e2b82',
    authDomain: 'entertainment-e2b82.firebaseapp.com',
    storageBucket: 'entertainment-e2b82.firebasestorage.app',
    measurementId: 'G-3E3JCFQL3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALDyr9u_idhnfeO8J3aJvcuY-3KyQq7do',
    appId: '1:386190378061:android:59fb5ad35319daf21a8804',
    messagingSenderId: '386190378061',
    projectId: 'entertainment-e2b82',
    storageBucket: 'entertainment-e2b82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdSnolO0NJFGioujzDRjP7QN-W8vatEis',
    appId: '1:386190378061:ios:f9d96d2a56a3e4901a8804',
    messagingSenderId: '386190378061',
    projectId: 'entertainment-e2b82',
    storageBucket: 'entertainment-e2b82.firebasestorage.app',
    iosBundleId: 'com.example.entertProjet01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdSnolO0NJFGioujzDRjP7QN-W8vatEis',
    appId: '1:386190378061:ios:f9d96d2a56a3e4901a8804',
    messagingSenderId: '386190378061',
    projectId: 'entertainment-e2b82',
    storageBucket: 'entertainment-e2b82.firebasestorage.app',
    iosBundleId: 'com.example.entertProjet01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm7Zj65lfPqFQ1pEScq773BBDS-2h1cmY',
    appId: '1:386190378061:web:d1d3a1c66c0bd09d1a8804',
    messagingSenderId: '386190378061',
    projectId: 'entertainment-e2b82',
    authDomain: 'entertainment-e2b82.firebaseapp.com',
    storageBucket: 'entertainment-e2b82.firebasestorage.app',
    measurementId: 'G-4SKKWL4WP1',
  );
}
